export const docsSidebar = [
  {
    title: 'Introduction',
    href: '#introduction',
    id: 'introduction',
    items: [
      {
        title: 'Introduction',
        href: '#introduction',
        id: 'introduction',
      },
    ],
  },
  {
    title: 'Details',
    href: '#details',
    id: 'details',
    items: [
      {
        title: 'What is Two-Factor Authentication?',
        id: 'what-is-two-factor-authentication',
      },
      {
        title: 'Why Use App?',
        id: 'why-use-app',
      },
      {
        title: 'How to set up',
        id: 'how-to-set-up',
      },
      {
        title: 'Managing Your Authenticator',
        id: 'managing-your-authenticator',
      },
      {
        title: 'Lost Your Phone',
        id: 'lost-your-phone',
      },
    ],
  },
  {
    title: 'Conclusion',
    href: '#conclusion',
    id: 'conclusion',
  },
]

export const policyConfigItems = [
  {
    title: 'Disable 2FA',
    text: 'Temporarily disable Two-Factor Authentication when necessary (for example, when you’re switching devices).',
  },
  {
    title: 'Change Authenticator App',
    text: 'If you need to switch phones or use a different device, you can update your 2FA settings here.',
  },
  {
    title: 'Regenerate QR Code',
    text: 'If you lose access to your Authenticator App, you can regenerate a new QR code to re-link your device.',
  },
]

export const whyChoosingUsItems = [
  {
    title: 'Enhanced Security',
    text: 'The time-sensitive code generated by the Authenticator App makes it nearly impossible for hackers to access your account, even if they have your password.',
  },
  {
    title: 'Offline Functionality',
    text: 'Unlike SMS-based 2FA, which requires an active phone connection, the Authenticator App works offline, ensuring you can always access your codes.',
  },
  {
    title: 'Convenient and Speedily',
    text: 'The app generates a new code every 30 seconds, ensuring real-time authentication for your login attempts.',
  },
]

export const lostYourPhoneItems = [
  {
    title: 'Use Backup Codes',
    text: 'During the setup process, we recommended saving backup codes. These one-time use codes can be entered instead of the 2FA code generated by the app.',
  },
  {
    title: 'Account Recovery',
    text: 'If you don’t have backup codes, use the account recovery process to regain access. You may be asked to verify your identity via email or other methods.',
  },
]
