export const featuresSidebar = [
  {
    title: 'Support',
    href: '#support',
    id: 'support',
    items: [
      {
        title: 'Product FAQs',
        id: 'product-faqs',
      },
      {
        title: 'Process FAQs',
        id: 'process-faqs',
      },
    ],
  },
  {
    title: 'Contact us',
    href: '#contact-us',
    id: 'contact-us',
  },
]

export const productFaqs = [
  {
    title: 'What is Authenticator and why should I use it?',
    text: 'Authenticator adds an extra layer of security to your account by requiring two forms of verification: something you know (your password) and something you have (a code from the eAuthenticator). This significantly reduces the risk of unauthorized access, even if your password is compromised.',
  },
  {
    title: 'How do I set up the Authenticator for my account?',
    text: 'To set up the Authenticator, simply download it from the App Store or Google Play, scan the QR code provided in your account settings, and enter the verification code generated by the app. This will link the app to your account and enable eAuthenticator for additional security.',
  },
  {
    title:
      'What should I do if I lose access to my phone or the eAuthenticator?',
    text: 'Once your identity has been successfully verified, you can reconfigure your 2FA settings on a new device. You’ll need to reinstall the eAuthenticator app and set it up again with your account.',
  },
  {
    title: 'Can I disable Authenticator once it’s set up?',
    text: 'Currently, it is not possible to disable the Authenticator once it’s been set up. Two-factor authentication (2FA) is designed to add an extra layer of security to protect your account. Disabling 2FA would compromise the security of your account, which is why we do not allow this option once it’s been activated.',
  },
]

export const processFaqs = [
  {
    title: 'How do I reset my password if I can’t access the Authenticator?',
    text: 'resetPassword',
  },
  {
    title: 'Can I switch devices and use the Authenticator on a new phone?',
    text: 'Yes, you can switch devices. To transfer your Authenticator to a new phone, open the app on the old device, go to account settings, and follow the instructions to transfer your 2FA credentials to the new phone.',
  },
  {
    title: 'What should I do if the Authenticator is not generating a code?',
    text: 'If your Authenticator app is not generating a code, first ensure that the time settings on your device are correct and synchronized automatically. The app relies on accurate time for generating codes, so check that your device’s time is set correctly. Make sure the Authenticator app is updated to the latest version from your device’s app store, as outdated versions may cause issues.',
  },
]
