import Image from 'next/image'
import {
  lostYourPhoneItems,
  policyConfigItems,
  whyChoosingUsItems,
} from '../constants'
import ImageDevice from '../images/device.png'
import ImageGroup from '../images/group.png'
import ImageInstruction from '../images/instruction.png'
import List from '@/components/static-layout/list'
import SectionLevel from '@/components/static-layout/sectionLevel'

export default function Detail() {
  return (
    <div className='flex flex-col gap-15'>
      <SectionLevel
        id='centralized-domain-management'
        title='Centralized Domain Management'
      >
        <div>
          Manage and configure all your domains in a centralized portal. You can
          add new domains, update existing ones, and delete domains that are no
          longer in use. This section also provides an overview of each domain&apos;s
          status and associated authentication configurations.
        </div>
      </SectionLevel>
      <SectionLevel
        id='what-is-two-factor-authentication'
        title='What is Two-Factor Authentication'
      >
        <div>
          Two-Factor Authentication (2FA) is an additional security measure that
          requires two forms of identity verification. The first is your
          password, and the second is a time-based one-time code (TOTP) which is
          generated by an Authenticator Application. Even if someone manages to
          obtain your password, they will still need access to your
          authenticator code to successfully log in.
        </div>
        <div>
          <Image alt='What is Two-Factor Authentication' src={ImageGroup} />
        </div>
      </SectionLevel>
      <SectionLevel
        id='why-use-app'
        title='Why Use the Authenticator Application?'
      >
        <div>
          The Authenticator Application provides an additional layer of defense
          that helps to protect your accounts from unauthorized access, even if
          someone obtains your password. Here’s why it’s critical:
        </div>
        <div className='flex items-center gap-4'>
          <div className='flex flex-col gap-4'>
            <List items={whyChoosingUsItems} itemClassName='max-w-[765px]' />
          </div>
          <div>
            <Image alt='Why Use the Authenticator Application?' src={ImageDevice} width={164} className='grow-0' />
          </div>
        </div>
      </SectionLevel>
      <SectionLevel
        id='how-to-set-up'
        title='How to Set Up the Authenticator Application'
      >
        <div>
          Getting started with the Authenticator App is quick and easy. Follow
          these simple steps to link your account and start using Two-Factor
          Authentication.
        </div>
        <div>
          <Image alt='How to Set Up the Authenticator Application' src={ImageInstruction} />
        </div>
      </SectionLevel>
      <SectionLevel
        id='managing-your-authenticator'
        title='Managing Your Authenticator Settings'
      >
        <div>
          Manage the Authenticator App effortlessly from your Account Settings
          page. Which you can do:
        </div>
        <div className='flex flex-col gap-4'>
          <List items={policyConfigItems} itemClassName='max-w-[765px]' />
        </div>
      </SectionLevel>

      <SectionLevel id='lost-your-phone' title='Lost Your Phone? No Problem!'>
        <div>
          If you lose your phone or cannot reach the Authenticator App, don’t
          worry! Follow these steps to regain access to your account:
        </div>
        <List items={lostYourPhoneItems} itemClassName='max-w-[765px]' />
      </SectionLevel>

      <SectionLevel id='conclusion' title='Conclusion'>
        <div>
          The Authenticator Application offers an easy-to-use and highly secure
          way to protect your account with Two-Factor Authentication (2FA). By
          combining something you know (your password) with something you have
          (your phone and the Authenticator App), it ensures that only you can
          access your sensitive data. Protect your account today by setting up
          the Authenticator App, and advanced your security practices!
        </div>
      </SectionLevel>
    </div>
  )
}
